nodeLinker: node-modules

compressionLevel: 9

enableColors: true

enableGlobalCache: false

enableTelemetry: false

nmMode: hardlinks-local

pnpEnableEsmLoader: true

packageExtensions:
  "cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
